name: Deploy to Azure DevOps

on:
  [push,pull_request]
  
jobs:
  deploy:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
    uses: Azure/pipelines@v1
    with:
      azure-devops-project-url: https://dev.azure.com/clouduserp295523e9/MyFirstProject
      azure-pipeline-name: 'gpkraju.actions'
      azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
